In [2]:
import pandas as pd

In [3]:
# Q1: Create a DataFrame using a dictionary

import pandas as pd

data = {
    "Name": ["Lalit", "Aman", "Riya", "Neha"],
    "Age": [20, 21, 19, 20],
    "City": ["Mathura", "Delhi", "Agra", "Jaipur"]
}

student_df = pd.DataFrame(data)

student_df

    Name  Age     City
0  Lalit   20  Mathura
1   Aman   21    Delhi
2   Riya   19     Agra
3   Neha   20   Jaipur

In [4]:
# Q2: Display the complete DataFrame

student_df

    Name  Age     City
0  Lalit   20  Mathura
1   Aman   21    Delhi
2   Riya   19     Agra
3   Neha   20   Jaipur

In [5]:
# Q3: Display the column names

student_df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [6]:
# Q4: Retrieve the Name column

student_df["Name"]

0    Lalit
1     Aman
2     Riya
3     Neha
Name: Name, dtype: object

In [7]:
# Q5: Retrieve the City column

student_df["City"]

0    Mathura
1      Delhi
2       Agra
3     Jaipur
Name: City, dtype: object

In [8]:
# Q6: Create a DataFrame with Name and City

new_df = student_df[["Name", "City"]]

new_df

    Name     City
0  Lalit  Mathura
1   Aman    Delhi
2   Riya     Agra
3   Neha   Jaipur

In [9]:
# Q7: Create a DataFrame using equal-length lists

book_data = {
    "Book": ["Python", "Java", "C++", "SQL"],
    "Author": ["A", "B", "C", "D"],
    "Price": [300, 400, 350, 250]
}

book_df = pd.DataFrame(book_data)

book_df

     Book Author  Price
0  Python      A    300
1    Java      B    400
2     C++      C    350
3     SQL      D    250

In [10]:
# Q8: Add the same Publisher to every row

book_df["Publisher"] = "ABC Publications"

book_df

     Book Author  Price         Publisher
0  Python      A    300  ABC Publications
1    Java      B    400  ABC Publications
2     C++      C    350  ABC Publications
3     SQL      D    250  ABC Publications

In [11]:
# Q9: Add SerialNo using np.arange(5)

import numpy as np

df = pd.DataFrame({
    "Name": ["A", "B", "C", "D", "E"]
})

df["SerialNo"] = np.arange(5)

df

  Name  SerialNo
0    A         0
1    B         1
2    C         2
3    D         3
4    E         4

In [12]:
# Q10: Delete the SerialNo column

df = df.drop("SerialNo", axis=1)

df

  Name
0    A
1    B
2    C
3    D
4    E

In [13]:
# Q11: Create a movie DataFrame

movie_df = pd.DataFrame({
    "Movie": ["Dangal", "3 Idiots", "PK", "Pathaan"],
    "Year": [2016, 2009, 2014, 2023],
    "Rating": [8.3, 8.4, 8.1, 5.8]
})

movie_df

      Movie  Year  Rating
0    Dangal  2016     8.3
1  3 Idiots  2009     8.4
2        PK  2014     8.1
3   Pathaan  2023     5.8

In [14]:
# Q12: Select Movie and Rating, and add Director

new_movie_df = movie_df[["Movie", "Rating"]].copy()

new_movie_df["Director"] = "Unknown"

new_movie_df

      Movie  Rating Director
0    Dangal     8.3  Unknown
1  3 Idiots     8.4  Unknown
2        PK     8.1  Unknown
3   Pathaan     5.8  Unknown

In [15]:
# Q13: Create a Series with selected indexes

city_series = pd.Series(
    ["Delhi", "Mumbai"],
    index=[0, 3]
)

city_series

0     Delhi
3    Mumbai
dtype: object

In [16]:
# Q14: Assign the Series to a new Branch column

branch_df = pd.DataFrame({
    "Name": ["A", "B", "C", "D"]
})

branch_df["Branch"] = city_series

branch_df

  Name  Branch
0    A   Delhi
1    B     NaN
2    C     NaN
3    D  Mumbai

In [18]:
# Q15: Read copied table data using clipboard

copied_df = pd.DataFrame(data)

copied_df

    Name  Age     City
0  Lalit   20  Mathura
1   Aman   21    Delhi
2   Riya   19     Agra
3   Neha   20   Jaipur

In [19]:
# Q16: Create employee DataFrame and select Employee and Experience

employee_df = pd.DataFrame({
    "Employee": ["A", "B", "C", "D", "E"],
    "Department": ["IT", "HR", "Sales", "IT", "Finance"],
    "Experience": [2, 4, 3, 5, 1]
})

new_employee_df = employee_df[["Employee", "Experience"]]

new_employee_df

  Employee  Experience
0        A           2
1        B           4
2        C           3
3        D           5
4        E           1

In [20]:
# Q17: Retrieve Department and display column names

employee_df["Department"]

employee_df.columns

Index(['Employee', 'Department', 'Experience'], dtype='object')

In [21]:
# Q18: Add the same Office value to every row

employee_df["Office"] = "Head Office"

employee_df

  Employee Department  Experience       Office
0        A         IT           2  Head Office
1        B         HR           4  Head Office
2        C      Sales           3  Head Office
3        D         IT           5  Head Office
4        E    Finance           1  Head Office

In [22]:
# Q19: Replace Office values using np.arange(5)

employee_df["Office"] = np.arange(5)

employee_df

  Employee Department  Experience  Office
0        A         IT           2       0
1        B         HR           4       1
2        C      Sales           3       2
3        D         IT           5       3
4        E    Finance           1       4

In [23]:
# Q20: Assign a partially indexed Series to Office

office_names = pd.Series(
    ["Delhi", "Mumbai", "Pune"],
    index=[0, 2, 4]
)

employee_df["Office"] = office_names

employee_df

  Employee Department  Experience  Office
0        A         IT           2   Delhi
1        B         HR           4     NaN
2        C      Sales           3  Mumbai
3        D         IT           5     NaN
4        E    Finance           1    Pune

In [24]:
# Q21: Delete the Office column

employee_df = employee_df.drop("Office", axis=1)

employee_df

  Employee Department  Experience
0        A         IT           2
1        B         HR           4
2        C      Sales           3
3        D         IT           5
4        E    Finance           1

In [25]:
# Q22: Create Product DataFrame with reordered columns

product_df = pd.DataFrame({
    "Product": ["Laptop", "Phone", "Tablet"],
    "Category": ["Electronics", "Electronics", "Electronics"],
    "Price": [50000, 30000, 20000]
})

new_product_df = product_df[["Price", "Product", "Category"]]

new_product_df

   Price Product     Category
0  50000  Laptop  Electronics
1  30000   Phone  Electronics
2  20000  Tablet  Electronics

In [26]:
# Q23: Request a column that does not exist

data = {
    "Name": ["A", "B", "C"],
    "Age": [20, 21, 22]
}

new_df = pd.DataFrame(data, columns=["Name", "Age", "City"])

new_df

  Name  Age City
0    A   20  NaN
1    B   21  NaN
2    C   22  NaN

In [27]:
# Q24: Retrieve a column containing a space

marks_df = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Total Marks": [80, 90, 85]
})

marks_df["Total Marks"]

0    80
1    90
2    85
Name: Total Marks, dtype: int64

In [30]:
# Q25: Read clipboard data and select three columns

print(copied_df.columns)

selected_df = copied_df.iloc[:, [0, 1, 2]]

print(selected_df)

Index(['Name', 'Age', 'City'], dtype='object')
    Name  Age     City
0  Lalit   20  Mathura
1   Aman   21    Delhi
2   Riya   19     Agra
3   Neha   20   Jaipur

In [ ]:
# Q26: Create course DataFrame and perform multiple operations

course_df = pd.DataFrame({
    "Student": ["A", "B", "C", "D", "E"],
    "Course": ["Python", "Java", "SQL", "Python", "Java"],
    "Score": [85, 90, 78, 88, 92]
})

print(course_df.columns)

print(course_df["Student"])

student_score_df = course_df[["Student", "Score"]]
print(student_score_df)

course_df["Batch"] = "2026"

course_df

In [31]:
# Q27: Add a Series and replace it with partial indexes

travel_df = pd.DataFrame({
    "Place": ["Delhi", "Agra", "Jaipur", "Mumbai", "Pune"]
})

travel_df["Code"] = np.arange(5)

print("After np.arange(5):")
print(travel_df)

code_series = pd.Series(
    [100, 200],
    index=[1, 4]
)

travel_df["Code"] = code_series

print("\nAfter assigning Series:")
print(travel_df)

After np.arange(5):
    Place  Code
0   Delhi     0
1    Agra     1
2  Jaipur     2
3  Mumbai     3
4    Pune     4

After assigning Series:
    Place   Code
0   Delhi    NaN
1    Agra  100.0
2  Jaipur    NaN
3  Mumbai    NaN
4    Pune  200.0

In [34]:
# Q28: Create a missing column and assign one common value

new_school_df = school_df[
    ["Student", "Class", "Section"]
].copy()

new_school_df["House"] = "Red"

print(new_school_df)

  Student  Class Section House
0       A     10       A   Red
1       B     10       B   Red
2       C     11       A   Red
3       D     11       B   Red
4       E     12       A   Red

In [35]:
# Q29: Add a partially indexed Series and then delete it

inventory_df = pd.DataFrame({
    "Product": ["Pen", "Book", "Bag", "Pencil", "Eraser"],
    "Price": [10, 50, 500, 5, 8]
})

stock_series = pd.Series(
    [20, 30],
    index=[1, 3]
)

inventory_df["Stock"] = stock_series

print("After adding Stock:")
print(inventory_df)

inventory_df = inventory_df.drop("Stock", axis=1)

print("\nAfter deleting Stock:")
print(inventory_df)

After adding Stock:
  Product  Price  Stock
0     Pen     10    NaN
1    Book     50   20.0
2     Bag    500    NaN
3  Pencil      5   30.0
4  Eraser      8    NaN

After deleting Stock:
  Product  Price
0     Pen     10
1    Book     50
2     Bag    500
3  Pencil      5
4  Eraser      8

In [40]:
# Q30: Read clipboard data and perform multiple DataFrame operations



lab_df = pd.DataFrame({
    "Name": ["Aman", "Rahul", "Lalit", "Priya", "Neha"],
    "Total Marks": [85, 90, 78, 92, 88],
    "City": ["Agra", "Delhi", "Mathura", "Jaipur", "Noida"]
})

print(lab_df)

print(lab_df.columns)

print(lab_df["Name"])

print(lab_df["Total Marks"])

small_df = lab_df[["Name", "Total Marks", "City"]]

print(small_df)

lab_df["Status"] = "Present"

print(lab_df)

lab_df = lab_df.drop("Status", axis=1)

print(lab_df)

    Name  Total Marks     City
0   Aman           85     Agra
1  Rahul           90    Delhi
2  Lalit           78  Mathura
3  Priya           92   Jaipur
4   Neha           88    Noida
Index(['Name', 'Total Marks', 'City'], dtype='object')
0     Aman
1    Rahul
2    Lalit
3    Priya
4     Neha
Name: Name, dtype: object
0    85
1    90
2    78
3    92
4    88
Name: Total Marks, dtype: int64
    Name  Total Marks     City
0   Aman           85     Agra
1  Rahul           90    Delhi
2  Lalit           78  Mathura
3  Priya           92   Jaipur
4   Neha           88    Noida
    Name  Total Marks     City   Status
0   Aman           85     Agra  Present
1  Rahul           90    Delhi  Present
2  Lalit           78  Mathura  Present
3  Priya           92   Jaipur  Present
4   Neha           88    Noida  Present
    Name  Total Marks     City
0   Aman           85     Agra
1  Rahul           90    Delhi
2  Lalit           78  Mathura
3  Priya           92   Jaipur
4   Neha           88    Noida